In [1]:


import numpy as np
from sklearn.datasets import fetch_openml 
 
mnist = fetch_openml('mnist_784', version=1)







In [2]:

print((np.array(mnist.data.loc[50]).reshape(28, 28) > 0).astype(int))
    
mnist.target





import pandas as pd  

# we create dataframes for features and labels

dfFeatures = pd.DataFrame(mnist.data)
dfLabels = pd.DataFrame(mnist.target)


#sorting labeels ascending

y = dfLabels.sort_values("class")

# reindexing feature df



indexes = y.index

"""for i in indexes:
    print(i)"""
    
    
X = dfFeatures.reindex(indexes)



# we have x (features) and y (labels)  





# we split our datasets

X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


# checking classes

y_train["class"].unique()





y_test['class'].unique()





# we divide our data with scikit-learn function

import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( dfFeatures, dfLabels, test_size=0.20, random_state=42)


# we check classes as in previous
y_train["class"].unique()
y_test["class"].unique()









[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 

['8', '4', '7', '0', '6', '2', '3', '9', '5', '1']
Categories (10, object): ['8', '4', '7', '0', ..., '3', '9', '5', '1']

In [3]:
#print(np.unique(y_train_0))

In [4]:
# learning

from sklearn.linear_model import SGDClassifier

#print((y_train["class"] == 0))

y_train_0 = (y_train["class"] == "0")
y_test_0 = (y_test["class"] == "0")


#print(y_train_0)
#print(len(y_train_0))


# we use sgd to classify 0

sgd_clf = SGDClassifier(random_state=42) 
sgd_clf.fit(X_train,y_train_0)






SGDClassifier(random_state=42)

In [5]:
# accuracy

from sklearn.metrics import precision_score

y_train_pred = sgd_clf.predict(X_train)
y_test_pred = sgd_clf.predict(X_test)

result1 = precision_score(y_train_0, y_train_pred)

In [6]:
result2 = precision_score(y_test_0 , y_test_pred)

In [7]:
resultArray = [result1,result2]
print(resultArray)


[0.9708487084870848, 0.9674922600619195]


In [8]:
# we pickle our accuracy 

import pickle

pickling_on = open("sgd_acc.pkl","wb")
pickle.dump(resultArray, pickling_on)
pickling_on.close()




In [9]:
# test for unpickling
""""
pickle_off = open("sgd_acc.pkl", 'rb')
data = pickle.load(pickle_off)
print(data)   """ 

'"\npickle_off = open("sgd_acc.pkl", \'rb\')\ndata = pickle.load(pickle_off)\nprint(data)   '

In [10]:
# validation

from array import array
from sklearn.model_selection import cross_val_score

score = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring="accuracy", n_jobs=-1)

# pickling

pickling_on = open("sgd_cva.pkl","wb")
pickle.dump(score, pickling_on)
pickling_on.close()

In [11]:
# test for unpickling
""""
pickle_off = open("sgd_cva.pkl", 'rb')
data = pickle.load(pickle_off)
print(data)"""

'"\npickle_off = open("sgd_cva.pkl", \'rb\')\ndata = pickle.load(pickle_off)\nprint(data)'

In [12]:
# we use sgd to classify all digits

sgd_m_clf = SGDClassifier(random_state=42,n_jobs=-1)
sgd_m_clf.fit(X_train, y_train)





/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SGDClassifier(n_jobs=-1, random_state=42)

In [13]:
# we create confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_m_clf, X_train, y_train, cv=3, n_jobs=-1)

conf_mx = confusion_matrix(y_train, y_train_pred)

#print(conf_mx)






[[5193    2   71   17   10   34   46    4  155   28]
 [   3 6121   49    9   14   17   20    8   30    6]
 [  42  109 4896  113   68   21   93   86  163   19]
 [  37   44  361 4312   26  497   28   86  224   93]
 [  15   31   49    2 5123    8   39   38   88  136]
 [  57   35   65  173  111 4069  127   36  298   69]
 [  56   33  204    3   66  122 4925    4   66    1]
 [  24   48   77   18  133   11    3 5225   44  207]
 [  47  216  705  130  133  446   77   68 3435  211]
 [  25   49   28   58  606   89    0  320  107 4256]]


In [14]:
# we pickle confusion matrix

pickling_on = open("sgd_cmx.pkl","wb")
pickle.dump(conf_mx, pickling_on)
pickling_on.close()


In [15]:
# test for unpickling
""""
pickle_off = open("sgd_cmx.pkl", 'rb')
data = pickle.load(pickle_off)
print(data)"""

'"\npickle_off = open("sgd_cmx.pkl", \'rb\')\ndata = pickle.load(pickle_off)\nprint(data)'