In [1]:
# we load the data

from sklearn.datasets import fetch_openml 
import numpy as np

mnist = fetch_openml('mnist_784', version=1, as_frame=False) 
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]



In [11]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


listToPickle = []

for i in range(8,13):
    
    kmeans = KMeans(n_clusters=i)
    kmeans.fit(X)
    
    score = silhouette_score(X, kmeans.labels_)
    
    listToPickle.append(score)
    print(score)
    print("\n")
    
    
print(listToPickle)


0.07338338455321246


0.0568152455429516


0.05878346099622555


0.05834532897886579


0.058201686228770005


[0.07338338455321246, 0.0568152455429516, 0.05878346099622555, 0.05834532897886579, 0.058201686228770005]


In [14]:
# we pickle our list

import pickle

with open('kmeans_sil.pkl', 'wb') as f:
    pickle.dump(listToPickle, f)
    
    
    

In [11]:
# we create matrix of errors

# in each row we should have one column which have high result, we are not interersted in diagonal values because it can not be classified in sequence

from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans



kmeans = KMeans(n_clusters=10)
kmeans.fit(X)

yPredicted = kmeans.predict(X)

matrix = confusion_matrix(y,yPredicted)





[6 0 4 ... 9 5 1]


In [15]:
# we pickle our list

#print(matrix)

#import pickle

# this is arbitrary

#with open('matrix.pkl', 'wb') as f:
 #   pickle.dump(matrix, f)
    
    
    

[[  42    7   72  285    9    2    4 1269 5045  168]
 [   6   10    9    8   10 4293 3527    7    0    7]
 [ 215   79  205  318 4867  429  433  237   56  151]
 [ 186   46 1043 4589  209  459   54  501   21   33]
 [3732 2187   19    0   29  182  234  262    9  170]
 [ 426  212 1135 2127    7  167  270 1839   60   70]
 [  67    4   15   37   57  203   45 1964   73 4411]
 [2086 4402   20    5   53  377  313   12   21    4]
 [ 210  187 4116 1181   52  335  324  329   37   54]
 [3456 2852   88   86   19  267   93   31   50   16]]


{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [13]:
# we find max indexes in each row

setToPickle = set()

for row in matrix:
    maxIndexInRow = np.argmax(row)
    setToPickle.add(maxIndexInRow)
    
    
print(setToPickle)



{0, 1, 3, 4, 6, 7, 8, 9}


In [18]:
# we pickle 

import pickle

with open('kmeans_argmax.pkl', 'wb') as f:
    pickle.dump(setToPickle, f)
    


In [21]:
# we check unpickling

#import pickle

#with open('kmeans_sil.pkl','rb') as f:
 #   loaded_obj1 = pickle.load(f)
    
#with open('kmeans_argmax.pkl','rb') as f2:
 #   loaded_obj2 = pickle.load(f2)
    
#print('loaded_obj1 is', loaded_obj1)
#print('loaded_obj2 is', loaded_obj2)



loaded_obj1 is [0.07338338455321246, 0.0568152455429516, 0.05878346099622555, 0.05834532897886579, 0.058201686228770005]
loaded_obj2 is {0, 1, 2, 3, 4, 5, 8, 9}


In [2]:
from sklearn.cluster import DBSCAN
import numpy as np

list2ToPickle = []

#dbscan = DBSCAN(eps=0.20, min_samples=5)
#dbscan.fit(X)

for x1 in X[:300]:
    for x2 in X:
        distance = np.linalg.norm(x1-x2)
        list2ToPickle.append(distance)

#list2ToPickle

[0.0,
 2387.111643807218,
 2773.149112471235,
 2554.8197588088283,
 2672.467212146858,
 2582.292392429641,
 2423.5917560513362,
 2169.9649766758907,
 2375.164625873331,
 2569.3078834581115,
 2139.8329374042264,
 2867.4593283950862,
 2666.0952721161334,
 2627.5760693079847,
 2377.237262033388,
 2627.911908721447,
 2452.252026199591,
 2305.5413680955717,
 2361.561771370802,
 2286.1800016621614,
 3153.737465294155,
 2661.511976302192,
 2430.517228904169,
 2562.744622470214,
 2413.886699909505,
 2731.21840942829,
 2490.662160952384,
 2388.085216234965,
 2841.7714545684353,
 2702.0340486381738,
 2590.299789599652,
 2627.523548895423,
 2393.2601195858338,
 2372.316378563365,
 2491.2386477413197,
 2608.1508775375705,
 2382.3291124443745,
 2612.5728697971276,
 2544.222867596312,
 2396.116232573036,
 2401.950041112429,
 2161.5577716082444,
 2387.229775283477,
 2143.5430949715005,
 2287.7751200675298,
 2617.665181034427,
 2534.771192829838,
 2496.3845857559686,
 2232.1556845345713,
 1917.8297630

In [3]:
# we need to delete 0 from list , because distance of element from itself is 0 and this is senseless info for us

list2WithoutZeros = [i for i in list2ToPickle if i != 0 ] # comprehension list
list2WithoutZeros.sort()  # we sort ascending

listOfTenMins = list2WithoutZeros[:10] # we use slice

#listOfTenMins


[279.26152617215286,
 304.37641170103836,
 317.5893575043093,
 328.7658741414626,
 333.4546445920344,
 352.89800226127664,
 355.1774204534967,
 358.07401469528617,
 359.64287842247063,
 360.42474942767177]

In [4]:
# we pickle 

import pickle

with open('dist.pkl', 'wb') as f:
    pickle.dump(listOfTenMins, f)
    



In [7]:
# we calc mean for later dbscan alg eps

import numpy as np

s = np.mean(listOfTenMins[:3])  # we take three min values to calc mean

eps1 = s
eps2 = 1.04 * s
eps3 = 1.08 * s

eps = [eps1,eps2,eps3]



In [9]:
# we use db scan alg
from sklearn.cluster import DBSCAN

listOfUqLabels = []

for e in eps:
    dbscan=DBSCAN(eps=e)
    dbscan.fit(X)
    labelsSet = set(dbscan.labels_.flat)
    listOfUqLabels.append(len(labelsSet))
    print(labelsSet)
    
print(listOfUqLabels)

{0, 1, 2, -1}
{0, 1, 2, 3, 4, 5, -1}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, -1}
[4, 7, 22]


In [15]:
# we pickle 

import pickle

with open('dbscan_len.pkl', 'wb') as f:
    pickle.dump(listOfUqLabels, f)
    


